title: A Bee in Bluebonnet
description:
baseurl: "/tbh-blog"
url: "https://quaintcabeza.github.io"

theme: minima

collections:
  blog:
    output: true
    permalink: /blog/:name/

navigation:
  - title: Plants
    url: "#"
    children:
      - title: Catalogue
        url: /plant-catalogue/
      - title: Gallery
        url: /gallery/
      - title: Wish List
        url: /wish-list/
      - title: Enemies
        url: /enemies/
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
